---
- hosts: webservers 
  remote_user: centos
  become: yes
  become_user: root
 
  tasks:
  - name: Atualizando o CentOS
    yum:
      name: '*'
      state: latest

  - name: Instalando o Repo Epel
    yum:
      name: epel-release
      state: present

  - name: Instalando o Nginx
    yum:
      name: nginx
      state: present

  - name: Habilitando o start do Nginx no boot
    service:
      name: nginx
      enabled: yes
 
  - name: Iniciando o Nginx
    service:
      name: nginx
      state: started

  - name: Copiando o arquivo index.html
    template:
      src: index.html.j2
      dest: /etc/www/html/index.html

  - name: Copiando o arquivo nginx.conf
    copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
    notify: Restartando o nginx
  
  handlers:
    - name: Restartando o nginx
      service:
        name: nginx
        state: restarted